[db.migrations]
schema_paths = [
  "./schemas/user_profiles.sql",
  "./schemas/files.sql",
  "./schemas/*.sql"
]

[functions.parse-file]
verify_jwt = false

[functions.convert-file]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.play-sentence]
verify_jwt = false
