[db.migrations]
schema_paths = [
  "./schemas/user_profiles.sql",
  "./schemas/files.sql",
  "./schemas/*.sql"
]

[auth]
site_url = "http://localhost:5173"
additional_redirect_urls = ["http://localhost:5173/update-password"]

[auth.captcha]
enabled = true
provider = "turnstile"
secret = "1x0000000000000000000000000000000AA"
